//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yProjectDataAccess
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using yProjectDataAccess;

    public partial class Question
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.Answers = new HashSet<Answer>();
        }

        public int qid { get; set; }
        public string qtitle { get; set; }
        public string qbody { get; set; }
        public string qtags { get; set; }
        public Nullable<int> qlikes { get; set; }
        public Nullable<int> qcomments { get; set; }
        public int uid { get; set; }
        public Nullable<System.DateTime> qdate { get; set; }
        public int User_uid { get; set; }
        public Nullable<int> qapprove { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
    }
}
